### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by maehr**
# Pull request

## Types of changes

- [ ] New feature (non-breaking change which adds functionality).
- [ ] Enhancement (non-breaking change which enhances functionality)
- [x] Bug Fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist

- [x] I have read the **[README](./README.md)** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Summary by CodeRabbit

- **Chores**
	- Improved readability of the `.prettierrc` configuration file.
	- Updated Node.js version compatibility in `package.json`.
	- Incremented multiple package versions in `devDependencies` for better compatibility and performance.
	- Added type safety to the Tailwind CSS configuration in `tailwind.config.ts`.

### CODE REVIEW

**Review by koilebeit — COMMENTED** [review]
Maybe I'm doing something wrong. But after `pnpm install` and `pnpm run prebuild` I get this:
image

**Comment by maehr** [comment]
> Maybe I'm doing something wrong. But after `pnpm install` and `pnpm run prebuild` I get this: image

The dev server does not work for me as well. But it builds. We would need to update skeleton to v3 which is a huge thing. I am out of ideas to fix this. We might be able to downgrade certain dependencies. But all of this would require a deep dive into the skeleton docs (or a time consuming upgrade to v3). What's you take on this?

PS: `npm run build && npm run preview` works for me.

**Comment by maehr** [comment]
@koilebeit PPS: Can you run the current configuration on `main` without problem?

**Comment by koilebeit** [comment]
> @koilebeit Can you run the current configuration on `main` without problem? I ran into the same problems with the actual config on `main`. I'll try to downgrade.

Yes, with the actual main it is the same problem

**Review by koilebeit — APPROVED** [review]
With this change, the dev server works again

**Pull request merged**
